# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11.4
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: ['--branch', 'main']
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-warn-return-any, --check-untyped-defs, --strict-equality, --strict-concatenate, --warn-unused-configs, --warn-redundant-casts, --warn-unused-ignores, --disallow-any-generics]
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
